### ISSUE TITLE
Linking issues with 1.1.0

### ISSUE THREAD

**Issue by vrabeux** [printdotio/printio-ios-sdk#412]
Using tags 1.1.0 or 1.1.9 cocoapods, I get the following error at linkage building step : 

```
duplicate symbol _OBJC_IVAR_$_PIOImageFilterView._toolbarView in:
    /workspace/dd/Pods/PrintIO/PrintIO.framework/PrintIO(PIOImageFilterView-C7E9E1109B822661.o)
duplicate symbol _OBJC_METACLASS_$_PIOImageFilterView in:
    /workspace/dd/Pods/PrintIO/PrintIO.framework/PrintIO(PIOImageFilterView-C7E9E1109B822661.o)
ld: 33 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation) 
```

**Comment by perisicboro** [comment]
Fixed. Will be available in new sdk, in a few hours.

**Comment by perisicboro** [comment]
@vrabeux https://github.com/printdotio/printio-ios-sdk/releases/tag/1.1.12

**Comment by vrabeux** [comment]
Sorry, did not solve the issue.

**Comment by perisicboro** [comment]
Try to download sdk manualy, without using pods.

**Comment by perisicboro** [comment]
And confirm that version is v1.1.12

**Comment by perisicboro** [comment]
Because we don't have PIOImageFilterView class anymore.

**Comment by AustenB** [comment]
@vrabeux let us know if downloading it manually fixes the issue.

**Comment by vrabeux** [comment]
So here is what I tried :
* remove all reference to printio on pods 
* clean
* delete Pods/* and workspace
* pod install 
* add manually 1.1.12 printio.framework and bundle.

But the the linking still fails.

**Comment by perisicboro** [comment]
What's the error now? It can't be the same.

**Comment by vrabeux** [comment]
Still the same about this FakeDelegate and PIOImageFilterView (that should not exists anymore). Moving to any version of 1.0.x works. I'll try to make a FRESH clone of our project with manual doxnload of the files. I'll keep you updated. Thanks for the help.

**Comment by vrabeux** [comment]
Here is the new - same error but instead of using pods it uses the downloaded framework with 1.1.12 tag.

```
duplicate symbol _OBJC_CLASS_$_PIOSettingsUtils in:
    app/PrintIO.framework/PrintIO(PIOSettingsUtils-DC95149310FDC260.o)
duplicate symbol _OBJC_METACLASS_$_PIOSettingsUtils in:
    app/PrintIO.framework/PrintIO(PIOSettingsUtils-DC95149310FDC260.o)
duplicate symbol _OBJC_CLASS_$_FakeDelegate in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._allProducts in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._appDelegate in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._assetsLibrary in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._enteredPromoCode in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._flickrContext in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._flickrRequest in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._globalVariantsDict in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._hpDelegate in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._imageBundle in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._isApp in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._isAppStarted in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._isCustomScreenPushed in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._orderData in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._pioCoupon in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._pioSettings in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._selectedGlobalColor in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._selectedGlobalTemplate in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._selectedGlobalTemplates in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._selectedImages in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._selectedProduct in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_METACLASS_$_FakeDelegate in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _kCheckTokenStep in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _kGetAccessTokenStep in:
    app/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_CLASS_$_PIOImageFilterEffectsView in:
    app/PrintIO.framework/PrintIO(PIOImageFilterEffectsView-C7E9E1109B822661.o)
duplicate symbol _OBJC_IVAR_$_PIOImageFilterEffectsView._buttonEffects in:
    app/PrintIO.framework/PrintIO(PIOImageFilterEffectsView-C7E9E1109B822661.o)
duplicate symbol _OBJC_IVAR_$_PIOImageFilterEffectsView._buttonMerge in:
    app/PrintIO.framework/PrintIO(PIOImageFilterEffectsView-C7E9E1109B822661.o)
duplicate symbol _OBJC_IVAR_$_PIOImageFilterEffectsView._buttonParameters in:
    app/PrintIO.framework/PrintIO(PIOImageFilterEffectsView-C7E9E1109B822661.o)
duplicate symbol _OBJC_IVAR_$_PIOImageFilterEffectsView._collectionView in:
    app/PrintIO.framework/PrintIO(PIOImageFilterEffectsView-C7E9E1109B822661.o)
duplicate symbol _OBJC_IVAR_$_PIOImageFilterEffectsView._toolbarView in:
    app/PrintIO.framework/PrintIO(PIOImageFilterEffectsView-C7E9E1109B822661.o)
duplicate symbol _OBJC_METACLASS_$_PIOImageFilterEffectsView in:
    app/PrintIO.framework/PrintIO(PIOImageFilterEffectsView-C7E9E1109B822661.o)
```
Looking at symbols I have : 
```
--( user@mbp )--( ~/workspace/printio-ios-sdk/PrintIO.framework/Versions/A )-- :)
--$ otool -L PrintIO  | grep FakeDelegate
PrintIO(FakeDelegate.o):
--( user@mbp )--( ~/workspace/printio-ios-sdk/PrintIO.framework/Versions/A )-- :)
--$ otool -L PrintIO  | grep PIOImageFilterEffectsView
PrintIO(PIOImageFilterEffectsView-C7E9E1109B822661.o):
PrintIO(PIOImageFilterEffectsView-C7E9E1109B822661.o):
```

**Comment by perisicboro** [comment]
@vrabeux This list will help. I'll upload a new sdk, in a hour, so you can try.

**Comment by perisicboro** [comment]
https://github.com/printdotio/printio-ios-sdk/releases/tag/1.1.13-dev

**Comment by vrabeux** [comment]
The error changed. Here is the new one :

```

duplicate symbol _OBJC_CLASS_$_FakeDelegate in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._allProducts in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._appDelegate in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._assetsLibrary in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._enteredPromoCode in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._flickrContext in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._flickrRequest in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._globalVariantsDict in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._hpDelegate in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._imageBundle in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._isApp in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._isAppStarted in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._isCustomScreenPushed in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._orderData in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._pioCoupon in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._pioSettings in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._selectedGlobalColor in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._selectedGlobalTemplate in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._selectedGlobalTemplates in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._selectedImages in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_IVAR_$_FakeDelegate._selectedProduct in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _OBJC_METACLASS_$_FakeDelegate in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _kCheckTokenStep in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
duplicate symbol _kGetAccessTokenStep in:
    app/Pods/PrintIO/PrintIO.framework/PrintIO(VCSelectPhotos.o)
    app/Pods/PrintIO/PrintIO.framework/PrintIO(FakeDelegate.o)
ld: 24 duplicate symbols for architecture x86_64

```

**Comment by perisicboro** [comment]
@vrabeux Please try this build, it should be fixed:
https://github.com/printdotio/printio-ios-sdk/releases/tag/1.1.14-dev

**Comment by vrabeux** [comment]
Solves it ! Thanks a lot !
